<?php

namespace dhope0000\LXDClient\Objects;

class RouteToNameMapping
{
    public $routesToName = [
        'dhope0000\\LXDClient\\Controllers\\Profiles\\CreateProfileController\\create' => 'Create Profile',
        'dhope0000\\LXDClient\\Controllers\\Profiles\\GetProfileController\\get' => 'Get Profile',
        'dhope0000\\LXDClient\\Controllers\\Profiles\\ReplaceProfileController\\replace' => 'Replace Profile',
        'dhope0000\\LXDClient\\Controllers\\Profiles\\RenameProfileController\\rename' => 'Rename Profile',
        'dhope0000\\LXDClient\\Controllers\\Profiles\\CopyProfileController\\copyProfile' => 'Copy profile',
        'dhope0000\\LXDClient\\Controllers\\Profiles\\DeleteProfileController\\delete' => 'Delete Profile',
        'dhope0000\\LXDClient\\Controllers\\Networks\\CreateNetworkController\\create' => 'Create Network',
        'dhope0000\\LXDClient\\Controllers\\Networks\\Tools\\FindIpAddressController\\find' => 'Find instance ip address',
        'dhope0000\\LXDClient\\Controllers\\Networks\\DeleteNetworkController\\delete' => 'Delete Network',
        'dhope0000\\LXDClient\\Controllers\\ProjectAnalytics\\GetGraphableProjectAnalyticsController\\get' => 'Get graphable analytics',
        'dhope0000\\LXDClient\\Controllers\\Deployments\\StartDeploymentController\\start' => 'Start Deployment',
        'dhope0000\\LXDClient\\Controllers\\Deployments\\DeleteDeploymentController\\delete' => 'Delete Deployment',
        'dhope0000\\LXDClient\\Controllers\\Deployments\\CreateController\\create' => 'Create Deployment',
        'dhope0000\\LXDClient\\Controllers\\Deployments\\StopDeploymentController\\stop' => 'Stop Deployment',
        'dhope0000\\LXDClient\\Controllers\\Deployments\\DeployController\\deploy' => 'Deploy Deployment',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Settings\\GetHostSettingsController\\get' => 'Get hosts settings',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Settings\\UpdateHostSettingsController\\update' => 'Update hosts config settings',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Settings\\UpdateSettingsController\\update' => 'Update hosts lxdmosaic settings',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\AddHostsController\\add' => 'Add Hosts',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\DeleteHostController\\delete' => 'Delete Host',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Certificates\\RenewHostCertificateController\\renew' => 'Renew LXDMosaic certificate with LXD',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Instances\\StartInstancesController\\start' => 'Start Instances',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Instances\\DeleteProxyDeviceController\\delete' => 'Delete proxy device',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Instances\\DeleteInstancesController\\delete' => 'Delete Instances',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Instances\\AddProxyDeviceController\\add' => 'Add proxy device',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Instances\\GetAllProxyDevicesController\\get' => 'Get all proxy devices',
        'dhope0000\\LXDClient\\Controllers\\Hosts\\Instances\\StopInstancesController\\stop' => 'Stop Instances',
        'dhope0000\\LXDClient\\Controllers\\Projects\\Users\\GetUsersWithAccessController\\get' => 'Get users with access to a host project',
        'dhope0000\\LXDClient\\Controllers\\Projects\\DeleteProjectController\\delete' => 'Delete Project',
        'dhope0000\\LXDClient\\Controllers\\Projects\\RenameProjectController\\rename' => 'Rename Project',
        'dhope0000\\LXDClient\\Controllers\\Projects\\CreateProjectController\\create' => 'Create Project',
        'dhope0000\\LXDClient\\Controllers\\Storage\\Volumes\\GetStorageVolumeController\\get' => 'Get storage volume info',
        'dhope0000\\LXDClient\\Controllers\\Storage\\Volumes\\CreateStorageVolumeController\\create' => 'Create storage volume',
        'dhope0000\\LXDClient\\Controllers\\Storage\\Volumes\\GetHostStorageVolumesController\\get' => 'Get all storage volumes on host',
        'dhope0000\\LXDClient\\Controllers\\Storage\\Volumes\\DeleteStorageVolumeController\\delete' => 'Delete storage volume',
        'dhope0000\\LXDClient\\Controllers\\Storage\\DeleteStoragePoolController\\delete' => 'Delete Storage',
        'dhope0000\\LXDClient\\Controllers\\Storage\\CreatePoolController\\create' => 'Create Storage',
        'dhope0000\\LXDClient\\Controllers\\CloudConfig\\UpdateController\\update' => 'Update Cloud Config',
        'dhope0000\\LXDClient\\Controllers\\CloudConfig\\CreateController\\create' => 'Create Cloud Config',
        'dhope0000\\LXDClient\\Controllers\\CloudConfig\\DeleteController\\delete' => 'Delete Cloud Config',
        'dhope0000\\LXDClient\\Controllers\\CloudConfig\\DeployController\\deploy' => 'Deploy Cloud Config',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Volumes\\AttachVolumesController\\attach' => 'Attach volume to instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Profiles\\RemoveProfileController\\remove' => 'Remove profile from instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Profiles\\AssignProfilesController\\assign' => 'Assign profiles to instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Comments\\SetInstanceCommentController\\set' => 'Set instance comment',
        'dhope0000\\LXDClient\\Controllers\\Instances\\DeleteInstanceController\\delete' => 'Delete Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\CopyInstanceController\\copy' => 'Copy instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\CreateImageController\\create' => 'Create image from instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\SetSettingsController\\set' => 'Set Instance Settings',
        'dhope0000\\LXDClient\\Controllers\\Instances\\RenameInstanceController\\rename' => 'Rename Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Snapshot\\RenameSnapshotController\\renameSnapshot' => 'Rename Instance Snapshot',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Snapshot\\DeleteSnapshotController\\deleteSnapshot' => 'Delete Instance Snapshot',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Snapshot\\RestoreSnapshotController\\restoreSnapshot' => 'Restore Instance Snapshot',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Snapshot\\ScheduleSnapshotsController\\schedule' => 'Schedule instance snapshots with LXD',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Snapshot\\TakeSnapshotController\\takeSnapshot' => 'Take Instance Snapshot',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Snapshot\\GetSnapshotsOverviewController\\get' => 'Get an overview of existing snapshots & configuration',
        'dhope0000\\LXDClient\\Controllers\\Instances\\StateController\\start' => 'Start Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\StateController\\stop' => 'Stop Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\StateController\\restart' => 'Restart Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\StateController\\freeze' => 'Freeze Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\StateController\\unfreeze' => 'UnFreeze Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\CreateController\\create' => 'Create Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\MigrateInstanceController\\migrate' => 'Migrate Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Backups\\DisableScheduledBackupsController\\disable' => 'Disable Instance Backup Schedule',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Backups\\DeleteLocalBackupController\\delete' => 'Delete Local Instance Backup',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Backups\\ScheduleBackupController\\schedule' => 'Set Instance Backup Schedule',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Backups\\BackupController\\backup' => 'Backup Instance',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Backups\\ImportBackupController\\import' => 'Import Remote Instance Backup',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Backups\\DeleteBackupController\\delete' => 'Delete Remote Instance Backup',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Files\\GetPathController\\get' => 'Get Instance Path Contents',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Files\\DeletePathController\\delete' => 'Delete Instance File',
        'dhope0000\\LXDClient\\Controllers\\Instances\\Files\\UploadFilesToPathController\\upload' => 'Upload File To Instance',
        'dhope0000\\LXDClient\\Controllers\\Backups\\RestoreBackupController\\restore' => 'Restore Local Backup To Host',
        'dhope0000\\LXDClient\\Controllers\\User\\AllowedProjects\\RevokeAccessController\\revoke' => 'Revoke a users access from a hosts project',
        'dhope0000\\LXDClient\\Controllers\\User\\AllowedProjects\\GrantAccessController\\grant' => 'Grant user access to a hosts project',
        'dhope0000\\LXDClient\\Controllers\\User\\AllowedProjects\\GrantAccessToProjectController\\grant' => 'Grant a user access to one hosts project',
        'dhope0000\\LXDClient\\Controllers\\User\\AllowedProjects\\GetUserAllowedProjectsController\\get' => 'Get a users allowed projects',
        'dhope0000\\LXDClient\\Controllers\\User\\DeleteUserController\\delete' => 'Delete a user',
        'dhope0000\\LXDClient\\Controllers\\Images\\Aliases\\RenameController\\rename' => 'Rename Image Alias',
        'dhope0000\\LXDClient\\Controllers\\Images\\Aliases\\CreateController\\create' => 'Create Image Alias',
        'dhope0000\\LXDClient\\Controllers\\Images\\Aliases\\DeleteController\\delete' => 'Delete Image Alias',
        'dhope0000\\LXDClient\\Controllers\\Images\\Aliases\\UpdateDescriptionController\\update' => 'Update Image Alias Description',
        'dhope0000\\LXDClient\\Controllers\\Images\\ImportRemoteImagesController\\import' => 'Import image from simplestream server',
        'dhope0000\\LXDClient\\Controllers\\Images\\DeleteImagesController\\delete' => 'Delete Images From Hosts',
        'dhope0000\\LXDClient\\Controllers\\InstanceSettings\\Ldap\\SaveLdapSettingsController\\save' => 'Save LXDMosaic Ldap Settings',
        'dhope0000\\LXDClient\\Controllers\\InstanceSettings\\FirstRunController\\run' => 'Run LXDMosaic First Run',
        'dhope0000\\LXDClient\\Controllers\\InstanceSettings\\ImageServers\\GetAllImageServersListController\\all' => 'Get all image servers list',
        'dhope0000\\LXDClient\\Controllers\\InstanceSettings\\ImageServers\\AddImageServerController\\add' => 'Add a new image server',
        'dhope0000\\LXDClient\\Controllers\\InstanceSettings\\ImageServers\\GetAllImageServersController\\all' => 'Get all image servers aliases',
        'dhope0000\\LXDClient\\Controllers\\InstanceSettings\\ImageServers\\DeleteImageServerController\\delete' => 'Delete an image server',
        'dhope0000\\LXDClient\\Controllers\\InstanceSettings\\SaveAllSettingsController\\saveAll' => 'Save LXDMosaic Settings',
        'dhope0000\\LXDClient\\Controllers\\InstanceSettings\\GetMySettingsOverviewController\\get' => 'Get My LXDMosaic Settings Overview',
        'dhope0000\\LXDClient\\Controllers\\Images\\ImportLinuxContainersByAliasController\\import' => 'Import LinunxContainer.Org Image',
    ];

    public function getControllerName(string $controller)
    {
        if (!isset($this->routesToName[$controller])) {
            return '';
        }
        return $this->routesToName[$controller];
    }
}
