CREATE TABLE `Recorded_Actions` (
    `RA_ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `RA_Date_Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `RA_Controller` VARCHAR(255) NOT NULL,
    `RA_Params` JSON NOT NULL
);
